name: Check Bundle Size
on:
  pull_request:
    branches: [main]
jobs:
  checkIfCodeownersUpdateNeeded:
    permissions:
      pull-requests: write # Used to add comment to PR
    name: Check if PR increases bundle size more than 5%
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn
      - name: Run Analyze
        run: yarn analyze
        env:
          NODE_OPTIONS: --max_old_space_size=4096



#         name: Check Bundle Size
# on:
#   pull_request:
#     branches: [main]
# jobs:
#   build-base:
#     name: Build base
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         ref: ${{ github.base_ref }}
  
#     - name: Install dependencies
#       run: npm ci
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
#     - name: Build
#       run: npm run build-demo
  
#     - name: Upload base stats.json
#       uses: actions/upload-artifact@v2
#       with:
#         name: base
#         path: ./demo/demo-dist/stats.json
#         retention-days: 1
