name: Check Bundle Size
on:
  pull_request:
    branches: [main]
jobs:
  checkBundleSizeChange:
    permissions:
      pull-requests: read
    name: Check if PR increases bundle size more than 5%
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn
      - name: Run Analyze
        run: ANALYZE=true yarn next-build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Check bundle size of select pages
        uses: actions/github-script@v6.4.0
        env:
          CURRENT_BRANCH: ${{ github.base_ref }}
          CURRENT_REPO: ${{ github.repository }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { checkBundleSize } = require('./.github/workflows/scripts/check_bundle_size.js');
            checkBundleSize({github, context, fetch, ignore});

