name: Block New Fragments
on:
  pull_request:
    branches: [main]
jobs:
  checkForNewFragments:
    name: Check for new fragments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get count of added fragments
        uses: actions/github-script@v6.4.0
        id: set-added-fragments-count
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { getAddedFragments } = require('./.github/workflows/scripts/check_for_new_fragments.js');
            return getAddedFragments({github, context, core});
  